version: "3.9"

services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
