from .base_store import BaseStore
from .americanas import Americanas
from .casas_bahia import CasasBahia
from .mercado_livre import MercadoLivre
from .amazon import Amazon
from .kabum import Kabum
from .magalu import Magalu
from .shopee import Shopee
from .terabyte import Terabyte
from .pichau import Pichau
